### ISSUE TITLE
Dragging a color control point on top of another makes it impossible to select either of them afterwards.

### ISSUE THREAD

**Issue by Twinklebear** [wilsonCernWq/TransferFunctionModule#1]
Starting from the default view:
![screenshot from 2017-11-30 11-30-16](https://user-images.githubusercontent.com/1522476/33447967-fd400afa-d5c1-11e7-9c65-93cbaa81ceca.png)

Drag the yellow control point on to the cyan:
![screenshot from 2017-11-30 11-30-46](https://user-images.githubusercontent.com/1522476/33447968-fd552a48-d5c1-11e7-8e97-67e033a39593.png)

After this the yellow is still drawn on top, but is no longer possible to select and drag by clicking the dot, while hovering the color box shows the cyan color value:

![screenshot from 2017-11-30 11-32-45](https://user-images.githubusercontent.com/1522476/33448050-366a3134-d5c2-11e7-8de8-70d0713e5983.png)

**Comment by wilsonCernWq** [comment]
Actually the problem here is the left button (cyan one) is draw before the right button (yellow one), so if they are overlapping, you are controlling the left button, which can only go to the left. 

I reverse the order of drawing the color pickers. It should make the interaction more obvious. Now the yellow button will go behind the cray one so one will know which button they are controlling.

**Comment by Twinklebear** [comment]
This was fixed a while ago I think
